### ISSUE TITLE
Permission error on entrypoint.sh

### ISSUE THREAD

**Issue by hnk** [Griesbacher/docker-omd-grafana#1]
When cloning this repo, `entrypoint.sh` loses its execute bit:
```
$ ls -la entrypoint.sh 
-rw-r--r--. 1 hnk hnk 66 15. Nov 11:46 entrypoint.sh
```
This leads to the following error when invoking docker run:
```
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/entrypoint.sh\\\": permission denied\"\n".
```

I'll submit a fix soon that changes the Dockerfile slightly to fix this ;)

**Comment by linhlt247** [comment]
@hnk thanks. @Griesbacher Can you process a pull request?

**Comment by Griesbacher** [comment]
Sorry, I've must have missed that one.
